name: 'Test Report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
      - name: Run git init to work around test reporter bug
        run: git init

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Go Test Results
          path: '*.xml'
          reporter: java-junit